# Generated by Django 6.0 on 2025-12-29 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_balance', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionAmount', models.FloatField(default=0)),
                ('transactionDate', models.DateTimeField(auto_now=True)),
                ('fraudDetection', models.BooleanField(default=False)),
                ('ReciverAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recived', to='api.useraccount')),
                ('SenderAccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent', to='api.useraccount')),
            ],
        ),
    ]
